name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 取得最新程式碼
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
      
    - name: 偵測 FTP 目錄結構 (除錯用)
      run: curl -s -l ftp://${{ secrets.FTP_SERVER }} --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"

      
    - name: 透過 FTP 同步檔案到主機
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # 暫時改回根目錄以避免 Timeout
        server-dir: ./
